version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - DB_TYPE=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=bank
      - DB_SSLMODE=disable
      - JWT_SECRET=your-secret-key
      - JWT_EXPIRATION=24
      - APP_ENV=production
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - bank-network

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bank
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bank-network

networks:
  bank-network:
    driver: bridge

volumes:
  postgres_data: 